; highlights.scm

"[QueryStringParams]" @keyword
"[FormParams]" @keyword
"[MultipartFormData]" @keyword
"[Cookies]" @keyword
"[Captures]" @keyword
"[Asserts]" @keyword
"[Options]" @keyword
(comment) @comment
(key_string) @property
(value_string) @string
(method) @function.builtin
(version) @constant.builtin
(quoted_string) @string
(regex) @string.special
(variable_name) @variable
"status" @function.builtin
"url" @function.builtin
"header" @function.builtin
"cookie" @function.builtin
"body" @function.builtin
"xpath" @function.builtin
"jsonpath" @function.builtin
"regex" @function.builtin
"variable" @function.builtin
"duration" @function.builtin
"sha256" @function.builtin
"md5" @function.builtin
"bytes" @function.builtin
"not" @operator
"equals" @operator
"==" @operator
"notEquals" @operator
"!=" @operator
"greaterThan" @operator
">" @operator
"greaterThanOrEquals" @operator
">=" @operator
"lessThan" @operator
"<" @operator
"lessThanOrEquals" @operator
"<=" @operator
"startsWith" @operator
"endsWith" @operator
"contains" @operator
"matches" @operator
"exists" @operator
"includes" @operator
"isInteger" @operator
"isFloat" @operator
"isBoolean" @operator
"isString" @operator
"isCollection" @operator
(integer) @number
(float) @number
(status) @number
(json_number) @number
"[" @punctuation.bracket
"]" @punctuation.bracket
":" @punctuation.delimiter
"," @punctuation.delimiter
"null" @constant.builtin
(boolean) @constant.builtin

(filter) @function.builtin
(json_key_string) @property
(json_string) @string
(json_number) @number
"{" @punctuation.bracket
"}" @punctuation.bracket
"{{" @punctuation.bracket
"}}" @punctuation.bracket
(file_value) @string.special
"cacert" @constant.builtin
"location" @constant.builtin
"insecure" @constant.builtin
"max-redirs" @constant.builtin
"retry" @constant.builtin
"retry-interval" @constant.builtin
"retry-max-count" @constant.builtin
(variable_option "variable") @constant.builtin
"verbose" @constant.builtin
"very-verbose" @constant.builtin
